### ISSUE TITLE
Port to Python 3

### ISSUE THREAD

**Issue by hannosch** [zopefoundation/RestrictedPython#12]
This is a placeholder issue to discuss/track the Python 3 port.

All the work is currently happening on the `Python3_update` branch. Updates to this branch are only done via reviewed pull requests.

**Comment by Daetalus** [comment]
Move the post from https://github.com/zopefoundation/Zope/issues/39

> Hi @hannosch 
> 
> Just FYI, I try to let [Pyston](https://github.com/dropbox/pyston) support Zope. But they didn't support the `compiler` package, which used by RestrictedPython. After some investigation. I try to use `ast` to replace `compiler` in RestrictedPython.
> 
> I start it by reading the source code of RestrictedPython. And then compare the ast before and after the `MutatingWalker`. Then use `ast.NodeTransformer` to do the same things. It basically a "reverse engineering". But the corner cases took me lots of time. More information is here: https://lab.nexedi.com/Daetalus/RestrictedPython-3.6.0/blob/c4652cb365edfe21e41c20bdf51c92dfab7a283f/src/RestrictedPython/notes.txt
> 
> It just a prototype, but in theory, it could work both Python 2/3 and Pyston. I think it's better to let you and other guys to know there already have some efforts to let RestrictedPython to support Python 3. Where to go on next is depend on you. (Just in case, I will resend this message to Zope dev mailist again).
> 
> Thanks all!

> There's a group of people who have been working on a branch there for the past 12 months using the same approach you took.

Would you mind to tell which branch? Seems the existed branches still using `compiler` package.

**Comment by hannosch** [comment]
@Daetalus it's stated in the issue description. The branch is `Python3_update`. I think it retains the old code and tests while the porting is underway. But I'm not an expert on how exactly this project is being ported, @icemac or @loechel might be able to explain this better.

**Comment by Daetalus** [comment]
@hannosch Sorry for no seeing this branch.

**Comment by loechel** [comment]
@Daetalus well no it did not depend anymore on a specific implementation of Python. The approach is in some way pretty simple, we do a transition from the compiler package to the ast package and do a transfrom of the AST to restrict certain features of Python. the builtin compile function of Python itself could compile AST into executable byte code. As this way we do not modify the byte code itself, it will run on all Python interpreters.

But yes, some of the test code still reley on inspecting the byte code. 

We do have a Sprint 31.01.2017-04.02.2017 in Innsbruck, and will move the Port foreward.
This Branch was started at the last Sprint there.

**Comment by stephan-hof** [comment]
@Daetalus, I know it is hard to navigate in the Python3_update branch.
The important bit there is this file: https://github.com/zopefoundation/RestrictedPython/blob/Python3_update/src/RestrictedPython/transformer.py

Tests for this file can be found here: https://github.com/zopefoundation/RestrictedPython/tree/Python3_update/tests

There you should find the new approach how RestrictedPython will work. As @loechel pointed out this approach will *only* use the ast module. The checks/restrictions relying on bytecode have been replaced there. Feel free to have a look at the transformer, feedback is welcome.

**Comment by loechel** [comment]
@hannosch @icemac did we want to close this issue now with release of RestrictedPython 4.0a1 and merge of the Python 3 Port branch into master?

**Comment by keul** [comment]
Sorry guys, that means RestrictedPython 4+ now supports Python 3?
This is not clear looking at *Changes* section.

**Comment by loechel** [comment]
@keul yes RestrictedPython 4 does support Python 2.7 and 3.4+

**Comment by icemac** [comment]
@keul Thank you for the hint. I added an item to the 4.0a1 release notes: 3cefd3cf381d5e5f6e30fad75c30993a3b31f67a
