### ISSUE TITLE
Support yield statements

### ISSUE THREAD

**Issue by aparamon** [zopefoundation/RestrictedPython#120]
**RestrictedPython 4.0b4**

To reproduce:

````python
from RestrictedPython import compile_restricted
source_code = """
def example():
    for i in range(6):
        yield i**2
"""
compile_restricted(source_code, '<inline>', 'exec')
````

````pytb
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    byte_code = compile_restricted(source_code, '<inline>', 'exec')
  File "C:\ProgramData\Anaconda3\lib\site-packages\RestrictedPython\compile.py", line 205, in compile_restricted
    raise SyntaxError(result.errors)
SyntaxError: ('Line 4: Yield statements are not allowed.',)
````

**Comment by aparamon** [comment]
Two main alternative ways to express generator idea are callbacks and returning collection, which are both sub-optimal (callbacks: not flexible, returning collections: non-efficient memory- and CPU-wise), unfortunately :-(

**Comment by djay** [comment]
If you want to stream a CSV file for example in a pythonscript, how do you do it?

**Comment by tseaver** [comment]
@djay Push rather than pull: you can invoke `response.write(text)` repeatedly.

**Comment by aparamon** [comment]
@tseaver Yes, but it is desirable to use not only pre-defined, but also custom generators as possible sources of `text`.

To me, there are 2 different aspects:

1. Creating generators inside restricted code for use in the outer (unrestricted) Python code.
2. Creating helper/utility generators for use inside restricted code.

It seems that 1. is what causes security implications. Having just 2. would already be a great feature; however I admit that given Python dynamic nature it's very hard/impossible to separate 2. from 1.

**Comment by icemac** [comment]
@aparamon Having thought a little about the security implication of `yield` I can imagine it could be possible to allow it in RestrictedPython. I am adding it to the todo list for the next Zope sprint.

**Comment by loechel** [comment]
I did a proposal for allowing yield statements in #136 and therefore generator functions in RestrictedPython.

But reading through Python Language Reference (https://docs.python.org/3/reference/expressions.html#yieldexpr) Yield expressions are deprecated in Python 3.7 and will be gone in Python3.8+ 

Should we take that into considerations?

**Comment by aparamon** [comment]
Your message might be mistakenly read that `yield` statements are going to be removed from Python really soon :-) It is of course not the case; [Python Language Reference](https://docs.python.org/3/reference/expressions.html#yieldexpr) says:
> Due to their side effects on the containing scope, yield expressions are not permitted **as part of the implicitly defined scopes used to implement comprehensions and generator expressions**.

It is natural/expected that RestrictedPython raises error for yield expressions used crazily inside list/dict comprehensions, once yield support is implemented.

**Comment by loechel** [comment]
Then, I did misread that. Might be, as English is not my first language and I think I get ill, at the moment, so did misinterpreted things.
