### ISSUE TITLE
Allow setitem and getitem

### ISSUE THREAD

**Issue by MeirShpilraien** [zopefoundation/RestrictedPython#168]
Hey,

I was just started to test this library a few days ago and I did not find any example for setitem and getitem implementation. I wonder what kind of security threats will raise if I will just allow everything in the SetItem and GetItem functions? something like this:
```
def SetItem(x, i, v):
    x[i] = v
    
def GetItem(x, i):
    return x[i]
```

Thanks, and thank you for developing this product.

**Comment by icemac** [comment]
`RestrictedPython` was architected with an object database in mind where some parts of the database might be restricted to some users (e. g. read only or even not accessible). That's why the methods `__getitem__` and `__setitem__` are not globally allowed.
If you do not have such restrictions, feel free to use the stub implementations which do no security checks.

**Comment by icemac** [comment]
@MeirShpilraien Did my comment answer your question?

**Comment by MeirShpilraien** [comment]
@icemac Yes it did, thanks you!!

Sorry for the late respond, closing the issue.

**Comment by ebagdasa** [comment]
can I enable only __setitem__ to support `a[key]` type of commands?

**Comment by ebagdasa** [comment]
@icemac, can I enable only __setitem__ on a particular class to support a[key] type of commands?

**Comment by icemac** [comment]
@ebagdasa Yes it is possible, see https://github.com/zopefoundation/RestrictedPython/blob/6c602c90cf8658cf1aaea660543228f127f6bbfd/src/RestrictedPython/transformer.py#L942-L954 how RestrictedPython translates subscription access to function calls.

This is the minimal function for `_getitem_`, it can be extended to check for the type of `ob`.

https://github.com/zopefoundation/RestrictedPython/blob/c53df5e2cbee6850bf37e5bdf8a5251eded6a839/src/RestrictedPython/Eval.py#L33-L35

To implement `__setitem__` you also need `_write_`. See the [documention](https://github.com/zopefoundation/RestrictedPython/blob/f5aacdc1eccd5c650f968d3b812192617f0e1069/docs/usage/policy.rst#implementing-a-policy) how the function has to be designed.

The to functions have to be added as `_getitem_` resp. `_write_` to the globals when calling `compile_restricted`.
