### ISSUE TITLE
defining a class throws __metaclass__ is not defined error

### ISSUE THREAD

**Issue by NotSoShaby** [zopefoundation/RestrictedPython#170]
I am trying to use RestrictedPython to allow users to create a class (that inherits from a base-class in my code). I get this error:

```
Traceback (most recent call last):
File "/Users/test_suite/primitive_tester.py", line 196, in check_dynamic_primitive
dynamic_primitives_compiled, compiled_result = DynamicPrimitiveLoader.load_primitive(dynamic_primitive)
File "/Users/primitive_matching_manager.py", line 207, in load_primitive
exec(byte_code)
File "<inline code>", line 3, in <module>
NameError: name '__metaclass__' is not defined
```

Now this comes from the `visit_ClassDef` function:

```
    def visit_ClassDef(self, node):
        """Check the name of a class definition."""
        self.check_name(node, node.name)
        node = self.node_contents_visit(node)
        if IS_PY2:
            new_class_node = node
        else:
            if any(keyword.arg == 'metaclass' for keyword in node.keywords):
                self.error(
                    node, 'The keyword argument "metaclass" is not allowed.')
            CLASS_DEF = textwrap.dedent('''\
                class {0.name}(metaclass=__metaclass__):
                    pass
            '''.format(node))
            new_class_node = ast.parse(CLASS_DEF).body[0]
            new_class_node.body = node.body
            new_class_node.bases = node.bases
            new_class_node.decorator_list = node.decorator_list
        return new_class_node
```

and i cannot understand the `__metaclass__` part.
trying to create a class like the one that is formed in the CLASS_DEF string results in the same error:

```
class MyClass(metaclass=__metaclass__):
    pass
```

Any ideas how to allow class creation in the received code?

**Comment by icemac** [comment]
The [documentation](https://restrictedpython.readthedocs.io/en/latest/usage/basic_usage.html#necessary-setup) says that you have to define a `__metaclass__` name in `__builtins__` to use classes in Python 3. (Also see the example in the section above the one linked to about how to use `__builtins__`.)

@NotSoShaby Does this answer your question?
Improvements for the documentation to make it easier understandable are always welcome.

**Comment by d-maurer** [comment]
NotSoShaby wrote at 2019-8-25 06:32 -0700:
>I am trying to use RestrictedPython to allow users to create a class (that inherits from a base-class in my code). I get this error:

`RestrictedPython` contains the basic infrastructure for restricted
Python code. Usually, it needs an external component to provide customization
and policy decisions. For Zope, this external component is
the package `AccessControl`.

When I remember right, I have seen recently, that `AccessControl` defines
`__metaclass__`.

If you use `RestrictedPython` alone, you must provide several definitions.
You could look at `AccessControl` for an example.

**Comment by NotSoShaby** [comment]
Hey @icemac and @d-maurer, thanks for the fast reply.  i dont know how i missed that, i went through the docs. this worked. I'm playing with the package right now and will like to contribute and improve the docs once I understand how I can use it better.
