### ISSUE TITLE
master branch currently dirty

### ISSUE THREAD

**Issue by loechel** [zopefoundation/RestrictedPython#172]
currently the master branch is dirty and tox fails due to flake8 errors and a non running python 3.8 test.

**Comment by loechel** [comment]
@icemac as I did #171 I saw that the master is currently dirty. 
I am a bit confused hot this could have happen, as a merge / pull request should only be allowed if all tests are green and that could / should not be if even tox is not green on a local run.

you could assign me again, I will then clean up and add more CI Setup to test.

**Comment by icemac** [comment]
As you found out yourself, the tests were not run on TravisCI 😢 .
