### ISSUE TITLE
Build fails for Python 3.8

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/RestrictedPython#179]
https://travis-ci.org/zopefoundation/RestrictedPython/jobs/584366714

**Comment by icemac** [comment]
It seems because of https://gitlab.com/python-devs/importlib_metadata/issues/86. A fix for it was released in 0.23. Restarting the TravisCI job.

**Comment by icemac** [comment]
Using the current version fixed the build: https://travis-ci.org/zopefoundation/RestrictedPython/jobs/584366714
