### ISSUE TITLE
iPython with RestrictedPython

### ISSUE THREAD

**Issue by ebagdasa** [zopefoundation/RestrictedPython#180]
I have got iPython to work with RestrictedPython, but need your advice on the next steps to make it configurable.

https://github.com/ebagdasa/ipython/commit/37cb4acfd4451531135d8320f72a22fe6602a10a 

To make the AST parsing work nicely, I had to change `compile.py`: 

https://github.com/zopefoundation/RestrictedPython/blob/6c602c90cf8658cf1aaea660543228f127f6bbfd/src/RestrictedPython/compile.py#L70-L73

to 

```
byte_code = compile(c_ast, filename, mode=mode,
                                    flags=flags,
                                    dont_inherit=dont_inherit
                                    )
```

**Comment by ebagdasa** [comment]
I have got it working with Jupyter too, but it feels hacky

**Comment by icemac** [comment]
What happens without your change in `compile.py`?

**Comment by ebagdasa** [comment]
still exploring, will update later
