### ISSUE TITLE
Global scope isn't updated when new function (or class) is defined

### ISSUE THREAD

**Issue by ssche** [zopefoundation/RestrictedPython#187]
Is there anything that can be done to allow the global namespace to be updated automatically? In (unrestricted) Python, function `example()` would have access to `c`, but in restricted python one is required to use global. In another example using metaclass, I tried to update `globals()[name] = ob` to allow classes to be available, but this didn't work (so I assume the same problem would apply for new functions).

Any idea would be appreciated.

```
from RestrictedPython import compile_restricted
from RestrictedPython import safe_globals

source_code = """

def c():
    return 1

def example():
    # required:
    # global c
    return c()

example()
"""

loc = {}
byte_code = compile_restricted(source_code, '<inline>', 'exec')
exec(byte_code, safe_globals, loc)

print (loc)
```

**Comment by kevinyang372** [comment]
Is there any update on this issue? I am also getting stuck on using restrictedpython to compile recursive functions as they are not added to the globals

**Comment by d-maurer** [comment]
> Is there any update on this issue? I am also getting stuck on using restrictedpython to compile recursive functions as they are not added to the globals

Unlike @icemac, I do not think this is a bug. In my view, you get what you called for.
You call for the execution of your source (defining `c` and `example`) with globals `safe_globals` and locals `loc`.  The definitions are put into `loc` which is not the `__globals__` of function `example`; as a consequence, `example` cannot access `c`.

If you want to use `loc` as "globals", you could achieve this via:
```
loc = safe_globals.copy()
exec(byte_code, log)
```

**Comment by kevinyang372** [comment]
@d-maurer Thank you! That does answer my question.
