### ISSUE TITLE
Remove 'setuptools' from setup.py

### ISSUE THREAD

**Issue by rahulbahal7** [zopefoundation/RestrictedPython#189]
There doesn't seem to be a reason to have setuptools in `install_requires`.

**Comment by jugmac00** [comment]
There are two imports from `setuptools`, see
https://github.com/zopefoundation/RestrictedPython/blob/c39cffe71dfc30630e946977735303d3a65b0383/setup.py#L16-L17

And both are necessary:
https://github.com/zopefoundation/RestrictedPython/blob/c39cffe71dfc30630e946977735303d3a65b0383/setup.py#L33
and
https://github.com/zopefoundation/RestrictedPython/blob/c39cffe71dfc30630e946977735303d3a65b0383/setup.py#L69

So I guess we can close this issue?

**Comment by rahulbahal7** [comment]
Does it need to be listed in `install_requires` for this?

**Comment by jugmac00** [comment]
Ah, ok - you edited your question.

So, it seems at least many if not all projects within `zopefoundation` list `setuptools` in the `install_requires` directive, but when I look for e.g. `attrs` or `flask` they don't.

Also, when I remove it and run `tox` it still works.

So, maybe it's some old habit or maybe it was necessary a long time ago?

I am not super familiar with `packaging`, so maybe someone else knows the answer.

**Comment by dopstar** [comment]
```python
from setuptools import find_packages 
```
this  line,  above, from `setup.py` depends of `setuptools` being already installed which is almost always the case (utils like `virtualenv` ensure this). If you create a virtual env and remove setuptools and then install restricted python from git repo onto the venv (not from pypi), then install would fail (see attached screenshot).

<img width="712" alt="Screenshot 2020-01-21 at 20 30 59" src="https://user-images.githubusercontent.com/2742870/72833052-a802cd80-3c8e-11ea-9d31-b406d922794c.png">

One would add a dependency on `install_requires` if its needed by the projects tooling/code-base not `setup.py`.

**Comment by icemac** [comment]
The `setuptools` dependency was added in f1c57a86d5b7cc6fa29f40b788499f3def51efa2 13 years ago. It does not seem to be needed any more, especially when using the wheel to install RestrictedPython.

**Comment by d-maurer** [comment]
Michael Howitz wrote at 2020-2-11 01:46 -0800:
>The `setuptools` dependency was added in f1c57a86d5b7cc6fa29f40b788499f3def51efa2 13 years ago. It does not seem to be needed any more, especially when using the wheel to install RestrictedPython.

I have added a `setuptools` dependency to many of my packages to avoid
a `buildout` warning. Hopefully, modern `buildout` version no longer need it.

**Comment by icemac** [comment]
@d-maurer Are the packages you mentioned packages having namespaces? (If I remember correctly `setuptools` was/is needed for them.)

**Comment by d-maurer** [comment]
Michael Howitz wrote at 2020-2-12 03:12 -0800:
>@d-maurer Are the packages you mentioned packages having namespaces? (If I remember correctly `setuptools` was/is needed for them.)

Yes.
