### ISSUE TITLE
PendingDeprecationWarning

### ISSUE THREAD

**Issue by frederikaalund** [zopefoundation/RestrictedPython#192]
I get this warning when using RestrictedPython:
```
[py.warnings] usr/lib/python3.8/ast.py:360: PendingDeprecationWarning: visit_Str is deprecated; add visit_Constant
```

I can see that you have [already noted](https://github.com/zopefoundation/RestrictedPython/blob/61d26b3b33027391c8781ff40131bac3fe8ed4c0/src/RestrictedPython/transformer.py#L546) that this is due to a deprecation in Python 3.8.

I suggest that you turn this note into `if sys.version_info >= (3, 8)`-logic to avoid the warning.

Let me know what you think.

**Comment by frederikaalund** [comment]
This also applies to `visit_Num` and `visit_NameConstant`.

**Comment by icemac** [comment]
I think the deprecated methods should be conditional for Python versions older than 3.8.
