### ISSUE TITLE
Is allowing built-in print unsafe?

### ISSUE THREAD

**Issue by MrNaif2018** [zopefoundation/RestrictedPython#211]
Hello, thank you very much for this project!

I have the following question, is the following considered safe:

```
class Policy(RestrictingNodeTransformer):
    def inject_print_collector(self, node, position=0):
        pass

    def visit_Name(self, node):
        node = self.node_contents_visit(node)
        if node.id != "print":
            self.check_name(node, node.id)
        return node
        
safe_globals = {
    ...omitted
    "print": print,
}
code = compile_restricted(source, "<string>", "exec", policy=Policy)
exec(code, safe_globals)
```

Basically I bypass the print function replacement and use it, because I need it working in my app without using `PrintCollector`.

I see [this example](https://github.com/zopefoundation/RestrictedPython/issues/205#issuecomment-745106322) which just prints the result afterwards, but why can't the same be done by a regular `print` function? Because of a potentially dangerous `file` argument?
In my case it is not easily possible to use the `printed` variable because I am executing user's code and I don't want to limit them by using non-standard print procedure, maybe it would require additional AST modification

UPD: In general I am not sure, why are some other functions limited and need re-implementation, such as `_inplacevar_`, `_write_`, `_unpack_sequence_`, for loops, etc. Do they also have some security issues if not limited, or it's just in case there might be an issue? As far as I know 3 critical things to limit are imports, getattr (disallow magic methods) and globals.

**Comment by d-maurer** [comment]
MrNaif2018 wrote at 2021-6-11 05:22 -0700:
> ...
>I see [this example](https://github.com/zopefoundation/RestrictedPython/issues/205#issuecomment-745106322) which just prints the result afterwards, but why can't the same be done by a regular `print` function? Because of a potentially dangerous `file` argument?

The primary user of `RestrictedPython` is `Zope` (via `AccessControl`).
This is a web application server where `stdout` typically has no meaningful
value.

Apart from that, `print` could be dangerous -- depending on whether
the restricted context could access a file object. It would then
be possible to fill up the underlaying file system.
Of course, a print collector could be spammed as well -- unless it
controls its size.

**Comment by MrNaif2018** [comment]
In our case it is more of a [CLI "compiler"](https://github.com/bitcartcc/bitccl/blob/better-compiler/bitccl/compiler.py) with some built-in functions provided, plus restrictions to make execution secure in case user (usually a merchant) has copy-pasted a script sample from unknown source. But in the future it is to be integrated into a web-app as well, but we can just redirect stdout via contextlib and use it. Or maybe in that case PrintCollector is a bit more useful. 
I indeed see that RestrictedPython is mostly AST-rewriting dangerous code to undefined names, and implementation is mostly at `AccessControl` package. But it highly depends on zope, so we would probably re-implement most of those functions. We need to allow many different things, for example *args, **kwargs or tuple unpacking is pretty useful, or in-place operators, but they access not defined functions. Looking at AccessControl it uses some Zope internals in those functions, so I am not sure if it's safe enough to just pass placeholder functions that allow execution (or override in policies) without additional checks?
Because except for RestrictedPython I don't see many options for allowing untrusted code execution

**Comment by MrNaif2018** [comment]
Closing this, as the original question has been answered, thank you. Although it would be good if it would be documented somewhere which things are safe to enable back or not. For now we will use [this setup of restricted python](https://github.com/bitcartcc/bitccl/blob/master/bitccl/compiler.py)
