### ISSUE TITLE
how to delete the restriction of print()

### ISSUE THREAD

**Issue by eswxxxa** [zopefoundation/RestrictedPython#212]
i want to delete the limitation of print() in RestrictedPython. i try many ways to do it and all failed.
I hope there is a step to delete this restriction.
thanks very much

**Comment by d-maurer** [comment]
eswxxxa wrote at 2021-7-5 06:43 -0700:
>i want to delete the limitation of print() in RestrictedPython. i try many ways to do it and all failed.
>I hope there is a step to delete this restriction.

`RestrictedPython` generally transforms the AST (= "Abstrct Syntax Tree")
to make potentially critical things (such as attribute/item access or print)
externally controllable.

`print` is almost surely transformed into `__print__`
(to make this certain look at the code).
In this case, you would provide your own `__print__` to control
how printing is handled.

**Comment by eswxxxa** [comment]
hi d-maurer, thanks again.
i used the script supported from you and found the print info can't be shown. i hope this three info can be printed to screen when the function was called. Could you please help me modify this script again?

from RestrictedPython import compile_restricted
from RestrictedPython.Guards import safe_builtins
from RestrictedPython.PrintCollector import PrintCollector

G = globals().copy()
G["__builtins__"] = safe_builtins
G["_print_"]      = PrintCollector

src = """
def f():
    a = 1
    b = 2
    print(a+b)
    c = 3
    d = 4
    print(c+d)
    e = 5
    f = 6
    print(e+f)
"""

code = compile_restricted(src, "<string>", "exec")
L = {}
exec(code, G, L)
L["f"]()

**Comment by eswxxxa** [comment]
> eswxxxa wrote at 2021-7-5 06:43 -0700:
> i want to delete the limitation of print() in RestrictedPython. i try many ways to do it and all failed. I hope there is a step to delete this restriction.
> `RestrictedPython` generally transforms the AST (= "Abstrct Syntax Tree") to make potentially critical things (such as attribute/item access or print) externally controllable. `print` is almost surely transformed into `__print__` (to make this certain look at the code). In this case, you would provide your own `__print__` to control how printing is handled.

hi d-maurer, thanks again.
i used the script supported from you and found the print info can't be shown. i hope this three info can be printed to screen when the function was called. Could you please help me modify this script again?

from RestrictedPython import compile_restricted
from RestrictedPython.Guards import safe_builtins
from RestrictedPython.PrintCollector import PrintCollector

G = globals().copy()
G["__builtins__"] = safe_builtins
G["_print_"]      = PrintCollector

src = """
def f():
    a = 1
    b = 2
    print(a+b)
    c = 3
    d = 4
    print(c+d)
    e = 5
    f = 6
    print(e+f)
"""

code = compile_restricted(src, "<string>", "exec")
L = {}
exec(code, G, L)
L["f"]()

**Comment by d-maurer** [comment]
eswxxxa wrote at 2021-7-5 21:38 -0700:
>i used the script supported from you and found the print info can't be shown.
> ...
>from RestrictedPython import compile_restricted
>from RestrictedPython.Guards import safe_builtins
>from RestrictedPython.PrintCollector import PrintCollector
>
>G = globals().copy()
>G["__builtins__"] = safe_builtins
>G["_print_"]      = PrintCollector

I have been wrong: "print" is handled a bit differently than
other features:
   `_print_` is assumed to be a factory which is called initially
   with `_getattr_`. For any `print` in the code the method
   `_call_print` of the resulting object is called.

This implies: in order to customize printing, you implement
your own `PrintCollector`, deriving from `RestrictedPython`'s
`PrintCollector` and overriding `_call_print`.
You bind your own `PrintCollector` to `_print_`.

**Comment by eswxxxa** [comment]
> eswxxxa wrote at 2021-7-5 21:38 -0700:
> i used the script supported from you and found the print info can't be shown. ... from RestrictedPython import compile_restricted from RestrictedPython.Guards import safe_builtins from RestrictedPython.PrintCollector import PrintCollector G = globals().copy() G["__builtins__"] = safe_builtins G["_print_"] = PrintCollector
> I have been wrong: "print" is handled a bit differently than other features: `_print_` is assumed to be a factory which is called initially with `_getattr_`. For any `print` in the code the method `_call_print` of the resulting object is called. This implies: in order to customize printing, you implement your own `PrintCollector`, deriving from `RestrictedPython`'s `PrintCollector` and overriding `_call_print`. You bind your own `PrintCollector` to `_print_`.

thanks d-maurer, i will try it

**Comment by eswxxxa** [comment]
> thanks d-maurer

thanks d-maurer, i can print the info. thanks a lot!!!!
