### ISSUE TITLE
Missing library stub for mypy check

### ISSUE THREAD

**Issue by mohankumaru** [zopefoundation/RestrictedPython#220]
Hi,
I am using RestrictedPython with zope AccessControl module, however Mypy complains " Skipping analyzing "RestrictedPython": module is installed, but missing library stubs or py.typed marker".
How do I get around this?

**Comment by jugmac00** [comment]
RestrictedPython is not typed, so a `py.typed` marker would not help at all.

Also, afaik nobody created a stub file.

So, in short, RestrictedPython is not typed yet. mypy offers several ways to ignore untyped libraries, see its documentation.

I do not think there are short/mid-term plans to provide type annotations.

**Comment by dataflake** [comment]
Closing this issue, the question has been answered. Simply configure mypy to ignore RestrictedPython.
