### ISSUE TITLE
Expressions in list comprehensions don't see external scope

### ISSUE THREAD

**Issue by aschleck** [zopefoundation/RestrictedPython#221]
Thank you for your work on this library!

## BUG/PROBLEM REPORT (OR OTHER COMMON ISSUE)

When a script defines a local variable and then seeks to access it inside of a list comprehension, the local variable is not visible.

### What I did:

```
from RestrictedPython import compile_restricted
from RestrictedPython.Eval import default_guarded_getiter

sample_code = """
x = 1
[x for y in [1]]
"""
supported_builtins = {}
supported_builtins['_getiter_'] = default_guarded_getiter
byte_code = compile_restricted(
    sample_code,
    filename='<inline code>',
    mode='exec'
)
exec(byte_code, {'__builtins__': supported_builtins}, {})
```

### What I expect to happen:

I expect the code to complete successfully.

### What actually happened:

```
Traceback (most recent call last):
  File "/my/script/test.py", line 16, in <module>
    exec(byte_code, {'__builtins__': supported_builtins}, {})
  File "<inline code>", line 3, in <module>
  File "<inline code>", line 3, in <listcomp>
NameError: name 'x' is not defined
```

### What version of Python and Zope/Addons I am using:

Python 3.10.2 on an macOS Monterey M1 Mac with RestrictedPython 5.2.

**Comment by d-maurer** [comment]
April Schleck wrote at 2022-2-17 14:11 -0800:
>## BUG/PROBLEM REPORT (OR OTHER COMMON ISSUE)
>
>When a script defines a local variable and then seeks to access it inside of a list comprehension, the local variable is not visible.
>
>### What I did:
>
>```
>from RestrictedPython import compile_restricted
>from RestrictedPython.Eval import default_guarded_getiter
>
>sample_code = """
>x = 1
>[x for y in [1]]
>"""
>supported_builtins = {}
>supported_builtins['_getiter_'] = default_guarded_getiter
>byte_code = compile_restricted(
>    sample_code,
>    filename='<inline code>',
>    mode='exec'
>)
>exec(byte_code, {'__builtins__': supported_builtins}, {})
>```

This is standard Python behavior -- not one of `RestrictedPython`:
```pycon:
>>> sc = """
... x = 1
... [x for y in [1]]
... """
>>>
>>> code = compile(sc, "<string>", "exec")
>>> exec(code, globals(), {})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 3, in <module>
  File "<string>", line 3, in <listcomp>
NameError: name 'x' is not defined
```

The cause:
names are defined in "locals"; the list comp accesses them via "LOAD_GLOBAL".


You can work around this behavior by copying `safe_globals`
and use this as only dict argument to `exec`.

**Comment by aschleck** [comment]
Ah thank you both so much for the quick response, leaving out the last argument to exec works perfectly. Sorry for the invalid bug.

The "wrap in a function" suggestion also works for #187 so tagging that here.
