### ISSUE TITLE
Can RestrictedPython be used in more complex projects?

### ISSUE THREAD

**Issue by mivanov1988** [zopefoundation/RestrictedPython#225]
Hello, I have been trying to use RestrictedPython for a more complex python project. The project consists of many files with relations between them. 

Here is an example of what I have been trying to achieve. But it seems that in this case, it doesn't work.

main.py
```python
from RestrictedPython import compile_restricted
from RestrictedPython import limited_builtins
from RestrictedPython import utility_builtins
from RestrictedPython.Guards import safe_builtins


def protected_getattr(obj, name, default=None):
    """Restricted method to get attributes."""
    return getattr(obj, name, default)


def _hook_import(name, *args, **kwargs):
    if name =='os': # now allow to import os
        raise RuntimeError('cannot import os')
    return __import__(name, *args, **kwargs)


builtins = safe_builtins.copy()
builtins.update(utility_builtins)
builtins.update(limited_builtins)
builtins['__import__'] = _hook_import
restricted_globals = {
    "_getattr_": protected_getattr,
    "__builtins__": builtins
}


if __name__ == '__main__':
    filename = f"test1.py"

    with open(filename, encoding="utf8") as fil:
        source = fil.read()
    code = compile_restricted(source, mode='exec')
    exec(code, restricted_globals)
```

test1.py
```python
from test2 import print_hi

print_hi("test")
```

test2.py
```python
import os


def print_hi(name):
    open('/etc/passwd')
    print(f'Hi, {name}')
```
The result of execution is `Hi test` rather than `cannot import os`.

Does RestrictedPython design for such use cases or it is just for a single file execution?

Thanks in advance!

**Comment by d-maurer** [comment]
Miroslav Ivanov wrote at 2022-4-14 04:29 -0700:
>Hello, I have been trying to use RestrictedPython for a more complex python project. The project consists of many files with relations between them.
> ...
>Does RestrictedPython design for such use cases?

Yes -- in principle.

**BUT** the only thing which `RestrictedPython` (really) does
is provide a means to compile a source with hooks for
elementary operations (e.g. attribute access, item access ...)
activated at runtime to allow a security policy implementation
to check the legality of such operations and
provide a different, more secure way to implement them.

If restricted Python imports a module (which implies you
have allowed this), then `RestrictedPython` does not magically
compile the source of this module for restricted use.
What happens during such an import is entirely determined
by your `__import__` implementation. In your example, your
essentially use Python's `__import__` which means that the module
gets compiled for **unrestricted** use (it `sys.modules` had not yet
a corresponding module).


Thus, if you would like to implement a modular application
where the modules are restricted, then you must implement
a corresponding `__import__` which uses `RestrictedPython`
to compile them in this way.

**Comment by mivanov1988** [comment]
I got it. Thank you!
