### ISSUE TITLE
RestrictedPython.tests package no longer installed ?

### ISSUE THREAD

**Issue by perrinjerome** [zopefoundation/RestrictedPython#231]
## BUG/PROBLEM REPORT (OR OTHER COMMON ISSUE)

I thought that the standard with zope packages was to include tests in the package, but the current versions of `RestrictedPython` no longer install the tests. With version `3.6.0`, `RestrictedPython.tests` was also installed, it's not the case with `5.1`. At that time, in the repository, the tests were located in [`src/RestrictedPython/tests`](https://github.com/zopefoundation/RestrictedPython/tree/3.6.0/src/RestrictedPython/tests), nowadays they are in [`tests`](https://github.com/zopefoundation/RestrictedPython/tree/5.2/tests) and they are not installed.

Is my understanding correct that it's expected to install the tests and  that they are now accidentally not installed because the tests were gradually moved from `src/RestrictedPython/tests` to `tests` in the making of version 4 ? In https://github.com/zopefoundation/zope.testrunner/issues/136#issuecomment-1159552141 @d-maurer gave a few arguments in favor of installing the tests. For reference, my use case is in an application applying some monkey patches to `RestrictedPython` and we run the original tests after applying the monkey patches to make sure the monkey patches do not break existing functionality.

### What I did:

I updated a Zope application that was using `RestrictedPython` version 3.6.0 to version 5.1

```
pip install RestrictedPython==5.1
python -c 'import RestrictedPython.tests' 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'RestrictedPython.tests
```

### What I expect to happen:

I expected the package `RestrictedPython.tests` to be installed, it was installed with version 3.6.0

### What actually happened:

The package `RestrictedPython.tests` was not installed.

**Comment by d-maurer** [comment]
Jérome Perrin wrote at 2022-8-23 06:38 -0700:
>I thought that the standard with zope packages was to include tests in the package, but the current versions of `RestrictedPython` no longer install the tests. With version `3.6.0`, `RestrictedPython.tests` was also installed, it's not the case with `5.1`. At that time, in the repository, the tests were located in [`src/RestrictedPython/tests`](https://github.com/zopefoundation/RestrictedPython/tree/3.6.0/src/RestrictedPython/tests), nowadays they are in [`tests`](https://github.com/zopefoundation/RestrictedPython/tree/5.2/tests) and they are not installed.

I do not know why the tests have been moved.

A potential cause could be: `RestrictedPython` is one of the few
`zopefoundation` projects designed for `pytest` (rather than
`zope.testrunner`) as test runner.
`zope.testrunner` likes when the tests are part of the installed tree
(it makes the command significantly simpler).
Not installing them might have been a way to reduce the risk to
run the tests with the wrong test runner.

Recently, (some) `pytest` fans massively argumented against installing
the tests. Maybe, someone acted on those arguments.

**Comment by perrinjerome** [comment]
Thanks for feedback, that's a good point that another difference is that this package also uses pytest.

I am trying https://github.com/zopefoundation/RestrictedPython/pull/232 to see if it seems more complicated than just moving the test folder around.

**Comment by perrinjerome** [comment]
> I am trying #232 to see if it seems more complicated than just moving the test folder around.

This attempt shows that it seems possible to move back the tests in `src/RestrcitedPython/tests`

**Comment by icemac** [comment]
Moving the tests outside of `src` was an experiment (like some other things) which happened while rewriting RestrictedPython in version 4 to port it to Python 3. I (still) see no need to keep the tests outside `src` and I am not even proposing to do so, but it seemed modern when it was introduced.
