### ISSUE TITLE
Unable to compile single expressions

### ISSUE THREAD

**Issue by kuwv** [zopefoundation/RestrictedPython#271]
## PROBLEM REPORT

Attempted a simple `compile_restricted` using `single`.

```python
x = 50
code = compile_restricted('x + 25', '<string>', 'single')
```

### What I did:

Attempted a simple comparison with `compile()`. Also, compared it with `exec`.

```python
x = 50
code = compile('x + 25', '<string>', 'single')
exec(code)

assert x == 75
```

### What I expect to happen:

Should be able to compile a single expression and execute with the associated side-effects similar to `compile()`.

### What actually happened:

```
SyntaxError: ('Line None: Interactive statements are not allowed.',)
```

### What version of Python and Zope/Addons I am using:
Python 3.11.8
RestrictedPython 7.0

**Comment by icemac** [comment]
The documentation is not clear about what this `single` mode is. There is even a test which asserts the error message you are seeing.

Maybe you have to use `eval` mode, even though it works totally different.

cc @loechel – Do you have an explanation for the `single` mode and the degree `RestrictedPython` supports it?

**Comment by d-maurer** [comment]
Michael Howitz wrote at 2024-2-26 23:51 -0800:
> ...
>cc @loechel – Do you have an explanation for the `single` mode and the degree `RestrictedPython` supports it?

"single" is mostly used as support for the interactive interpreter;
it compiles a single line containing a sequence of simple statements
or one complex statement (potentially spanning multiple lines).

I do not think, we need support for it in `RestrictedPython`.

**Comment by loechel** [comment]
@icemac as we ported RestrictedPython the Interactive mode was not implemented.

It could be easily done by adding a ``visit_Interactive`` to the `transformer.py`. 
Documentation for it: https://docs.python.org/3/library/ast.html#ast.Interactive

**Comment by kuwv** [comment]
@loechel Thank you.

I would appreciate this being implemented. Should I submit an MR or will someone else here assist?

**Comment by loechel** [comment]
@kuwv I could do a merge request and bring it into one of the next releases, if @icemac agrees.

I guess, you @kuwv don't have signed the Zope Contributer Agreement, it would take more overhead for you to submit a Merge Request to get it included.

**Comment by icemac** [comment]
@loechel I agree that you can come up with a PR.

**Comment by loechel** [comment]
merge request created, after some more tests, I have seen, that the invocation is a bit different than asked for.

```python
code = compile_restricted('x = 4 * 6', filename="<string>", mode="single")
locals = {}
exec(code, {}, locals)
assert locals["x"] == 24
```

to explain. exec does not return anything but prints.

**Comment by kuwv** [comment]
> merge request created, after some more tests, I have seen, that the invocation is a bit different than asked for.
> 
> 
> 
> ```python
> 
> code = compile_restricted('x = 4 * 6', filename="<string>", mode="single")
> 
> locals = {}
> 
> exec(code, {}, locals)
> 
> assert locals["x"] == 24
> 
> ```
> 
> 
> 
> to explain. exec does not return anything but prints. 

Yeah, that's correct. The 'tests/helper.py' demonstrates an exec return.
