### ISSUE TITLE
Q: citing RestrictedPython

### ISSUE THREAD

**Issue by ocramz** [zopefoundation/RestrictedPython#280]
Hi! this project is helping us a lot in research and we'd love to cite it in publications. Is there a list of core contributors and/or a preferred citing format for this? Thanks a lot!

**Comment by dataflake** [comment]
There is no dedicated list of contributors. The closest would be to look at the list of commits at https://github.com/zopefoundation/RestrictedPython/commits/master/ to see who is active. I don't know anything about citing formats, sorry.

**Comment by icemac** [comment]
Or even https://github.com/zopefoundation/RestrictedPython/graphs/contributors which provides a summarized view of all the contributors.

**Comment by loechel** [comment]
Well can we say that, @icemac and myself have done most of the rewrite and current status, I don't know who was the original author. 

For me (@loechel - Alexander Loechel) as someone in academic citations is always a good thing. 

There are some hint on how to cite a github repository: https://academia.stackexchange.com/questions/14010/how-do-you-cite-a-github-repository

**Comment by icemac** [comment]
Please do not forget @stephan-hof, who did some of the heavy lifting and worked on edge cases no-one else has thought of.

**Comment by ocramz** [comment]
Thank you for all your input!

If repository owners are interested in making this a bit more systematic, it is possible to connect a GH account with Zenodo (research infra hosted by CERN) or Figshare, which will create a unique DOI every time a github release is created.  The DOI is a de facto standard, easy to cite and look up.
