### ISSUE TITLE
Use SPDX license identifier for metadata

### ISSUE THREAD

**Issue by cdce8p** [zopefoundation/RestrictedPython#291]
## FEATURE REQUEST
[PEP 639](https://peps.python.org/pep-0639/) recommends the use of SPDX license identifiers. I believe it would make sense to adopt them. The required change is minimal.

https://spdx.org/licenses/ZPL-2.1.html

https://github.com/zopefoundation/RestrictedPython/blob/642202897b419a74b1cb1756315936b45fb75e78/setup.py#L30

```diff
-      license='ZPL 2.1',
+      license='ZPL-2.1',
```

**Comment by loechel** [comment]
Done on https://github.com/zopefoundation/RestrictedPython/commit/07950f933194c0bb96fb6c48b023a4ba195eb60d
