### ISSUE TITLE
Tuple unpacking to local variables should be allowed

### ISSUE THREAD

**Issue by tseaver** [zopefoundation/RestrictedPython#65]
E.g., from the Products.PythonScripts fibonacci test:

```python
l = []
a, b = 0, 1
while b < 100000000:
    l.append(b)
    a, b = b, a+b  # fails with error
return l
```

The error is:

```python
> /home/tseaver/.buildout/eggs/cp27m/RestrictedPython-4.0a1-py2.7.egg/RestrictedPython/tests/verify.py(45)verify()
-> verify(ob)
(Pdb) d
> /home/tseaver/.buildout/eggs/cp27m/RestrictedPython-4.0a1-py2.7.egg/RestrictedPython/tests/verify.py(42)verify()
-> verifycode(code)
(Pdb) d
> /home/tseaver/.buildout/eggs/cp27m/RestrictedPython-4.0a1-py2.7.egg/RestrictedPython/tests/verify.py(50)verifycode()
-> _verifycode(code)
(Pdb) d
> /home/tseaver/.buildout/eggs/cp27m/RestrictedPython-4.0a1-py2.7.egg/RestrictedPython/tests/verify.py(110)_verifycode()
-> (code.co_filename, line))
(Pdb) l
105  	            if not (window[0].opname == "CALL_FUNCTION" and
106  	                    window[1].opname == "ROT_TWO" and
107  	                    window[2].opname == "LOAD_GLOBAL" and
108  	                    window[2].arg == "_getiter_"):
109  	                raise ValueError("unguarded unpack sequence at %s:%d" %
110  ->	                                 (code.co_filename, line))
111  	
112  	        # should check CALL_FUNCTION_{VAR,KW,VAR_KW} but that would
113  	        # require a potentially unlimited history.  need to refactor
114  	        # the "window" before I can do that.
115  	
```

**Comment by icemac** [comment]
@tseaver Do you have a link to the code of the failing test?
It  still uses the `verify` function which does some checks on byte-code level. These checks are no longer correct for tuple unpacking as it is now implemented using [_unpack_sequence_](https://github.com/zopefoundation/RestrictedPython/blob/master/src/RestrictedPython/transformer.py#L1011) with a different byte code than before.

We dropped using `verify` on other places as we were not able to adapt it. See also the [PendingDeprecationWarning](https://github.com/zopefoundation/RestrictedPython/blob/master/src/RestrictedPython/tests/verify.py#L35) when using this function.

**Comment by stephan-hof** [comment]
As far as I can see the following is causing problems:
https://github.com/zopefoundation/Products.PythonScripts/blob/master/src/Products/PythonScripts/tests/testPythonScript.py#L62

So the tests of Products.PythonScripts use this `verify` on each script before they run it. Currently there is no `verify` available so the only suggestion I have is removing this line.

Let my try to explain why the `verify` was dropped and not ported.
The new implementation of RestrictedPython is not using bytecode transformations at all, only AST modifications. Implementing a good verify is not so trivial. Bytecode in python 2/3 differs a little in some places. Furthermore we have too keep up with changes to it with newer versions of python. 
The new unittests here (https://github.com/zopefoundation/RestrictedPython/tree/master/tests) are using a different approach to ensure that RestrictedPython does what it should. By really executing the code.

**Comment by tseaver** [comment]
I am fine with ditching the `verify()` call, as long as the new RP still allows that `fibonacci` to run as expected (with the tuple unpacking).

**Comment by tseaver** [comment]
I can't tell whether we have tests that tuple unpacking works:  are the examples in `RestrictedPython/tests/` still checked?

**Comment by icemac** [comment]
@tseaver The tests in `src/RestrictedPython/tests` are still run but only on the old implementation. We are about to rewrite them in the `tests` directory which are run on both implementations. There is also a test for [tuple unpacking](https://github.com/zopefoundation/RestrictedPython/blob/master/tests/transformer/test_assign.py#L9). (Even unpacking with star arguments is now supported, thanks to @stephan-hof!)
