### ISSUE TITLE
pytest conftest.py and pytest_plugins

### ISSUE THREAD

**Issue by loechel** [zopefoundation/RestrictedPython#70]
Is this an issue to our code? https://twitter.com/hackebrot/status/873083574676733953

If I understand it right you should not import fixtures, as imports will create an internal copy of that fixture object which in our case is a function object and could mess up with python cache so even byte code cache.

Also I have seen that it strongly recommended to have no __init__.py in tests, see also: https://docs.pytest.org/en/latest/goodpractices.html#choosing-a-test-layout-import-rules

**Comment by icemac** [comment]
@loechel Thank you for bringing this up as it can help in other projects. Currently we are not using any fixtures in `RestrictedPython` so importing them is not a problem here.

I do not see a strong recommendation against making a folder containing test modules a package in the link to the py.test documentation. It even says: "If you need to have test modules with the same name, you might add \_\_init\_\_.py files to your tests folder and subfolders, changing them to packages".

**Comment by loechel** [comment]
Thanks
