### ISSUE TITLE
Usage of random under safe_builtins + utility_buildins

### ISSUE THREAD

**Issue by ladal1** [zopefoundation/RestrictedPython#72]
I ran into problem I wasn't able to solve while trying to use random module in compiled code.
I have simple test code to try it out:
`data = "x = random.random()"`
that is then compiled:
```
bytecode = compile_restricted(data, '<inline>', 'exec')
exec(bytecode, allowed_globals, allowed_locals)
```
(allowed locals is: `allowed_locals{'__builtins__': {**safe_builtins, **utility_builtins}}`)
which has inside itself loaded module random if i check it

but when I try and execute it, I get `NameError: name '_getattr_' in not defined`

I couldn't find if there is any example of how to use utility_buildins, and I am just doing it completely wrong (probably)

**Comment by ladal1** [comment]
I am an idiot, sorry ignore this, forgot to actually define _getattr_ to use

**Comment by rnixx** [comment]
Hi @ladal1,

I actually ran into the same issue, and actually the code example in the docs not works as provided, so docs should be updated to provide a fully functional example.

**Comment by icemac** [comment]
@rnixx Can you tell which lines of the documentation should be improved?
