### ISSUE TITLE
ModuleNotFoundError: No module named 'SelectCompiler'

### ISSUE THREAD

**Issue by davidemoro** [zopefoundation/RestrictedPython#94]
Hi,

I'm trying to use restricted python in a non zope/plone piece of software and I get an import error:
> >>> import RestrictedPython
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/davide/workspaces/play_requests/.tox/py36/lib/python3.6/site-packages/RestrictedPython/__init__.py", line 17, in <module>
>     from SelectCompiler import *
> ModuleNotFoundError: No module named 'SelectCompiler'

Tried with:
* python3.6
* RestrictedPython==3.6.0

**Comment by davidemoro** [comment]
With 4.0.b2 works fine, thanks

**Comment by icemac** [comment]
RestrictedPython <= 4.0.dev0 does not support Python 3.
